name: Build

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  build:
    name: Build
    strategy:
       matrix:
          java: [1.8]
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        uses: eskatos/gradle-command-action@v1
        with:
           arguments: build
           dependencies-cache-enabled: true
      - name: Store HTML test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-html
          path: "**/reports/tests/"
      - name: Store XML test report
        uses: actions/upload-artifact@v2
        with:
          name: test-results-xml
          path: "**/test-results/"




