name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - id: get_version
        name: Get Version
        uses: battila7/get-version-action@v2
      - name: Release
        uses: eskatos/gradle-command-action@v1
        env:
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.GRADLE_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        with: 
          arguments: release "-PreleaseVersion=${{ steps.get_version.outputs.version }}"
          dependencies-cache-enabled: true


